name: Auto merge develop into main

on:
  workflow_run:
    workflows: ["Run Tests", "Fix Code Style"]
    types:
      - completed

permissions:
  contents: write

jobs:
  merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch branches
        run: |
          git fetch origin main
          git fetch origin develop

      - name: Merge develop into main
        run: |
          git checkout main
          git merge origin/develop --no-edit

      - name: Push changes to main
        run: git push origin main
